---

- name: Update the apt cache
  apt:
    cache_valid_time: 3600
    update_cache: yes

- name: ClamAV | Install packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: 
    - clamav
    - clamav-daemon
  when: clamav_packages
