#!/bin/sh

HOST=`cat /etc/hostname`

echo "$(date) - $CLAM_VIRUSEVENT_VIRUSNAME > $CLAM_VIRUSEVENT_FILENAME" >> /var/log/clamav/infected.log

echo "$(date) - $CLAM_VIRUSEVENT_VIRUSNAME found in $CLAM_VIRUSEVENT_FILENAME on server $HOST" | mail -s "Virus Found" it@taxameter.nl 

# mv -f $CLAM_VIRUSEVENT_FILENAME /opt/clamav-utils/quarantine


# Here we need to set a mail message
#sudo -u yourUserName DISPLAY=:0.0 notify-send "Virus Found $CLAM_VIRUSEVENT_VIRUSNAME" "$CLAM_VIRUSEVENT_FILENAME has been removed"
